version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - API_KEY=${API_KEY}
      - MODEL=${MODEL}
    volumes:
      - .:/app